name: C/C++ CI

on: ["push"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jurplel/install-qt-action@v3.2.1
    - uses: snickerbockers/cmake-configure@prerel1
    - run: |
        cmake -Bbuild && cmake --build build --parallel
    - run: |
        ./build/untitled2_test
